# This is basically the standard DBT config file.
name: "ai_assistant_pipeline"
version: "1.0.0"
profile: "ai_assistant_pipeline"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  # Nothing here. We're configuring models inside them using dbg.config()
