[project]
name = "ai-assistant-pipeline"
version = "1.0.0"
description = "A DBT pipeline to set up the data needed for the AI assistant demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dbt-core>=1.10.11", "dbt-snowflake>=1.10.0"]
